version: "3"
services:
  eureka-server-sr:
    image: eureka-server
    build: ./eurekaserver
    container_name: eureka-server-sr
    ports:
      - "8761:8761"
    networks:
      - app-network





  api-gateway-sr:
    image: api-gateway
    build: ./api-gateway
    container_name: api-gateway-sr
    ports:
      - "8090:8090"
    networks:
      - app-network
    depends_on:
      - eureka-server-sr


  authentication-sr:
    image: authentication-service
    build: ./authentication
    container_name: authentication-sr
    ports:
      - "8789:8789"
    networks:
      - app-network
    depends_on:
      - eureka-server-sr
      - api-gateway-sr

  book-sr:
    image: book-service
    build: ./book-service
    container_name: book-sr
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - eureka-server-sr
      - api-gateway-sr
      - authentication-sr

  review-sr:
    image: review-service
    build: ./review-service
    container_name: review-sr
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - eureka-server-sr
      - api-gateway-sr
      - authentication-sr
      - book-sr

  # mysqldb:
  #   image: mysql:8
  #   networks:
  #     - app-network
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=organizationdb

networks:
  app-network: